export { default as ArcadeApp } from './components/ArcadeApp'
export { default as GameShell } from './components/GameShell'
export { default as Leaderboard } from './components/Leaderboard'
export { GAMES, getGame } from './lib/games'
export { getLeaderboard, submitScore, getPersonalBest } from './lib/api'
export type { ArcadeUser, GameConfig, GameProps, LeaderboardEntry, SubmitScorePayload } from './lib/types'
